# fly.toml app configuration file generated for expert-parakeet on 2023-07-05T21:31:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expert-parakeet"
primary_region = "ams"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
