(ns util.strings-test
  (:require
    [clojure.test :as t :refer [deftest testing]]
    [test-extensions :refer [test-with-check]]
    [util.strings :refer [shorten]]))


(deftest test-shorten
  (testing "Autogenerated tests for shorten"
    (test-with-check `shorten {:clojure.spec.test.check/opts {:num-tests 200}})))
