(ns util.strings-test
  (:require [test-extensions :refer [test-with-check]]
            [clojure.test :as t :refer [deftest testing]]
            [util.strings :refer [shorten]]))

(deftest test-shorten
  (testing "Autogenerated tests for shorten"
    (test-with-check `shorten {:clojure.spec.test.check/opts {:num-tests 200}})))
