name: Clojure CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check formatting
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :check-format
      - name: run linter
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :lint
      - name: run tests
        env:
          OAUTH_CLIENT_ID: ''
          OAUTH_CLIENT_SECRET: ''
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :test-runner
      - name: Build the whole application
        run: docker build .