name: Clojure CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: install clojure
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
          chmod +x posix-install.sh
          sudo ./posix-install.sh
      - name: check formatting
        run: clojure -M:check-format
      - name: run linter
        run: clojure -M:lint
      - name: compile cljs
        run: clojure -X:compile-cljs
      - name: run tests
        run: clojure -X:test
        env:
          OAUTH_CLIENT_ID: ''
          OAUTH_CLIENT_SECRET: ''
      - name: build uber jar
        run: clojure -T:build uber
