name: Clojure CI

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check-format 
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :clj-format check
      - name: kondo-check
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :clj-kondo --lint src test
      - name: run tests
        uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :test-runner
      - name: Build the whole application
        run: docker build .